### ISSUE TITLE
bug in index.php

### ISSUE THREAD

**Issue by arpit456jain** [Spectrum-CETB/LesKollab#101]
**Describe the bug**
When the admin logged in and go on index.php the button is showing login instead of logout

https://user-images.githubusercontent.com/55352601/115229087-3aaf4800-a130-11eb-9b33-3c5634625d99.mp4

**Expected behavior**
It will show logout there and on clicking on that the admin should be logout

**Comment by arpit456jain** [comment]
@rupeshmohanty kindly assign me this issue

**Comment by rupeshmohanty** [comment]
@arpit456jain Admin login should not be connected to the user login page, Both user side and admin side should work parallely.

**Comment by arpit456jain** [comment]
Ok you can close to this issue for now 👍

**Comment by arpit456jain** [comment]
@rupeshmohanty there is also one more bug



https://user-images.githubusercontent.com/55352601/115260777-adc8b680-a150-11eb-8332-4d5f613538a5.mp4

**Comment by rupeshmohanty** [comment]
@arpit456jain You gave the wrong URL, it should be /admin/admin_login.php

**Comment by arpit456jain** [comment]
> @arpit456jain You gave the wrong URL, it should be /admin/admin_login.php

@rupeshmohanty i don't give the wrong url 
There is wrong url is in code you can check it on your system .

**Comment by arpit456jain** [comment]
> @arpit456jain You gave the wrong URL, it should be /admin/admin_login.php

I just try to access admin dashboard that's why i give the url for dashboard it should redirect me to login page

@rupeshmohanty

**Comment by rupeshmohanty** [comment]
@arpit456jain See it works perfectly on my system!
![image](https://user-images.githubusercontent.com/43889891/115410382-36f2f280-a210-11eb-9665-3dc8c5816a3a.png)

**Comment by arpit456jain** [comment]
> @arpit456jain See it works perfectly on my system!
> ![image](https://user-images.githubusercontent.com/43889891/115410382-36f2f280-a210-11eb-9665-3dc8c5816a3a.png)

@rupeshmohanty did you give the url 

http://localhost/lesscolab/admin/admin_dashboard.php  ??

**Comment by rupeshmohanty** [comment]
Are you trying to access the dashboard page from the URL?

**Comment by arpit456jain** [comment]
> Are you trying to access the dashboard page from the URL?

Yes

**Comment by rupeshmohanty** [comment]
Yeah you can put a check on the dashboard page which redirects the user to the admin-login if not logged in yet or redirects to the dashboard page if there is a session.
