### ISSUE TITLE
Changes required in navbar on index.php(Home Page).

### ISSUE THREAD

**Issue by hardikvarshney** [Spectrum-CETB/LesKollab#103]
1. Links on navbar are not in correct order.
2. Missing! "FAQ's" link on navbar.   
3. There should be "Home" link on navbar, which is also missing.

**Comment by hardikvarshney** [comment]
#107

**Comment by arpit456jain** [comment]
@hardikvarshney bro I think the pr related to this issue is already got merged so please close this issues
