### ISSUE TITLE
Register not get the user to his profile

### ISSUE THREAD

**Issue by Raghad-Khaled** [Spectrum-CETB/LesKollab#111]
**Describe the bug**

When user Register that show message register successfully but not tack the user to his profile and need to login to do that and that is not good user experience.

I can fix this small Problem

**Comment by arpit456jain** [comment]
I think its ok to login after registration as registration is a one time process so need to make it complicated .

**Comment by rupeshmohanty** [comment]
@Raghad-Khaled Its not required for the user to get logged in once he/she registers.
