### ISSUE TITLE
Hover Effect, Bug, Logo size

### ISSUE THREAD

**Issue by RuchiGitHu** [Spectrum-CETB/LesKollab#112]
Describe the issue: 1. he navbar looks simple, this can be more creative and effective for user experience to add hover in navbar.
2. The content of landing page is mixing with image, the last two lines of content is going to mislead image.
3. Size of logo of website is too small then navbar at least and other content of website.

How to reproduce the issue: **I can add hover in navbar, Fix bug, can increase the size of logo so that logo can be seen easly.**

Proof of issue(Screenshot/Location where to find the issue): **Mention where to find the issue, also attach proof of issues is available**
![image](https://user-images.githubusercontent.com/71754179/116003225-bf133680-a61a-11eb-8f85-164e22053201.png)

Bug :
![image](https://user-images.githubusercontent.com/71754179/116003239-c9353500-a61a-11eb-9fe9-441b516e166b.png)

Please assign this issue to me under gssoc21.

**Comment by ishubham21** [comment]
Hi @RuchiGitHu! You can proceed with the issue, however, the hover action is not required. So please implement the rest of the changes. 
Thank you.
