### ISSUE TITLE
About Us block background color.

### ISSUE THREAD

**Issue by RuchiGitHu** [Spectrum-CETB/LesKollab#128]
**Is your feature request related to a problem? Please describe.**
![image](https://user-images.githubusercontent.com/71754179/116813614-2d537e00-ab72-11eb-8012-bda702eb8367.png)
When we see about us, its looking like just content of it is written in website page but when we look carefully its in box which is not highlighted as it should be due to background color of box.

**Describe the solution you'd like**
I want to change background color of about us box, so that it can be more visible as it should be.

**Describe alternatives you've considered**
Na

**Additional context**
![image](https://user-images.githubusercontent.com/71754179/116813748-ff226e00-ab72-11eb-8d9a-7c5e612f4b93.png)
![image](https://user-images.githubusercontent.com/71754179/116813760-119ca780-ab73-11eb-935f-349d254f2dbd.png)
Please let me know if images is visible to you...

**Comment by rupeshmohanty** [comment]
@RuchiGitHu This is not a required issue.
