### ISSUE TITLE
Adding a Confirmation Alert Before Logging Out From Admin Dashboard

### ISSUE THREAD

**Issue by arpit456jain** [Spectrum-CETB/LesKollab#136]
Adding a Confirmation Alert Before Logging Out From Admin Dashboard like this
<img width="361" alt="alert" src="https://user-images.githubusercontent.com/55352601/117486941-f7eecc00-af87-11eb-968c-969a712a872c.png">

**Comment by arpit456jain** [comment]
@rupeshmohanty I remember  I had added this alert in user dashboard but its not present there . Did anyone remove it intentionally ?

**Comment by rupeshmohanty** [comment]
@arpit456jain Not sure if someone removed it or not. Can you implement it again?

**Comment by arpit456jain** [comment]
Yes ofcourse @rupeshmohanty  should i creat 2 issue for implementing it on user dashboard and admin dashboard or should i implement it one issue?
