### ISSUE TITLE
Adding a chatbot

### ISSUE THREAD

**Issue by Debashish-hub** [Spectrum-CETB/LesKollab#14]
Describe the issue: **Adding a chatbot**
Expected behavior: **Chatbot is one of the common things present in website which increases the customer interaction. There could be some person to reply back or a bot to reply to faqs**

I would like to work on it as a participant of GSSOC'21

**Comment by rupeshmohanty** [comment]
Hey @Debashish-hub,
Are you gonna use an external API for that or are you gonna make one?

**Comment by Debashish-hub** [comment]
I will be using an external API, as I don't have much knowledge to create it.
