### ISSUE TITLE
About Us page missing

### ISSUE THREAD

**Issue by CoderGaurav01** [Spectrum-CETB/LesKollab#15]
In the nav-bar the About Us link is unresponsive.
Can create a modal or create a link to new page or add further block of div element in the landing page itself

**Comment by CoderGaurav01** [comment]
As a GSSOC'21 participant I would love to work on this issue.

**Comment by rupeshmohanty** [comment]
Hey Gaurav,
I have assigned this issue to you!

**Comment by CoderGaurav01** [comment]
which option should be better : 
- including the content in the landing page
- creating a new about-us page
- using a modal ?
And what should be the content?

**Comment by rupeshmohanty** [comment]
Go with whichever option you like and for now put Lorem Ipsum text in the About us page.
