### ISSUE TITLE
Add responsiveness to index.php

### ISSUE THREAD

**Issue by Ananya-Misra** [Spectrum-CETB/LesKollab#166]
I would like to add responsiveness to the index.php
![Untitled](https://user-images.githubusercontent.com/70848031/119648611-4c76c000-be3f-11eb-9f2d-7e0dfdc9d944.png)

**Comment by prathamesh3707** [comment]
Can , you assign it to me?

**Comment by Ananya-Misra** [comment]
@prathamesh3707 I have created this issue so that it could be assigned to me.

**Comment by prathamesh3707** [comment]
ok , np
