### ISSUE TITLE
improve the schema (add new relation in SQL )

### ISSUE THREAD

**Issue by Raghad-Khaled** [Spectrum-CETB/LesKollab#18]
Describe the issue: in the relation Projects attribute tag not an atomic value I suggest to normalize it to be good schema and (we can filter project after that acording their stack) 
How to reproduce the issue: create new relation(table) that has stacks and new relation to has projects and their stacks (it is more clear in image below) and this edit will need some changes in post-project.php file 
Expected behavior: the database schema will be good and we can add new feature that filer projects with stack
Proof of issue(Screenshot/Location where to find the issue): 
the schema now:
<img width="750" alt="Old" src="https://user-images.githubusercontent.com/60848147/111043516-af190c00-844b-11eb-90fe-585c36e23c9d.PNG">

then schema should be:
<img width="443" alt="New2" src="https://user-images.githubusercontent.com/60848147/111043553-d2dc5200-844b-11eb-8535-20bd73dff61b.PNG">

the ER
https://lucid.app/lucidchart/invitations/accept/5427fda2-4eb8-4072-9a16-0ae48ad70ea0

**Comment by rupeshmohanty** [comment]
Can you explain me how exactly the output is gonna be?

**Comment by Raghad-Khaled** [comment]
it will not change any thing in Ui of the project it will only change how the schema store the data so after that we can add filter on the projects by their stack
and I think in more feature that enable user to search for projects suits their stack and that will not be applicable without change the data base schema 
I hope that is clear now

**Comment by rupeshmohanty** [comment]
For that you have to write a backend code too. So changing the database will not be sufficient to fix this issue.

**Comment by Raghad-Khaled** [comment]
yes I know , I mentioned that need  changes in post-project.php file

**Comment by rupeshmohanty** [comment]
Okay I am assigning this issue to you!
