### ISSUE TITLE
Spacing issue in post an idea form.

### ISSUE THREAD

**Issue by satcasm** [Spectrum-CETB/LesKollab#20]
If you go to the ```post an idea``` link. The screenshots field in getting merged with the input field.

Screenshot for reference:
![image](https://user-images.githubusercontent.com/56315878/111058692-1075c500-84b6-11eb-9b41-27de11eb3a35.png)

Would like to improve upon it under GSSOC' 21.
Thanks!

**Comment by hardikvarshney** [comment]
As a GSSoC' 21 participant. I would like to work on it.

**Comment by anika-001** [comment]
Go ahead @satcasm

**Comment by Nishayadav-bit** [comment]
Hey !
I am a GSSOC'21 participant.
Can i work on this issue.

**Comment by sakshi300699** [comment]
@Nishayadav-bit This issue has already been assigned. Please look for some other issue.

**Comment by satcasm** [comment]
Closing the issue as PR is merged.
