### ISSUE TITLE
Hamburger menu

### ISSUE THREAD

**Issue by satcasm** [Spectrum-CETB/LesKollab#21]
Would like to change the color of  hamburger icon so that navigation becomes easy for smaller devices.
Currently it's not clearly visible , you have to hover over it , then only you can see the icon.

Screenshot Reference:
![image](https://user-images.githubusercontent.com/56315878/111060138-c2b28a00-84c0-11eb-8191-e8536300af57.png)

Would like to work on it under GSSOC' 21.
Thanks!

**Comment by rupeshmohanty** [comment]
Hey @satcasm, this issue has been assigned to you!

**Comment by satcasm** [comment]
Hey @rupeshmohanty is adding a level tag on the issues not necessary ? 
I was reading the GSSOC guidelines and it suggested that each issue should be divided on 3 levels, then only the PR would considered valid. Feel free to correct me if I am wrong.
Thanks!

**Comment by rupeshmohanty** [comment]
Yeah I just saw that. Let me just add that

**Comment by satcasm** [comment]
Can you tell me why there are 2 assets folders?

**Comment by satcasm** [comment]
Hey @rupeshmohanty what should I do about the ```db.php``` file? Should I add it in a```.gitignore``` file?

**Comment by rupeshmohanty** [comment]
Yes it should be added to the ```.gitignore``` file, cause you this project has different database configuration.

**Comment by satcasm** [comment]
Closing the issue as PR is merged.
