### ISSUE TITLE
changes in the read me file.

### ISSUE THREAD

**Issue by manognyaa** [Spectrum-CETB/LesKollab#27]
I am gssoc'21 Participant.

I would like to correct the spelling ("collborators") => ("collaborators") in this read me file. 

![image](https://user-images.githubusercontent.com/77045147/111118297-982f0280-858e-11eb-81cc-b71f02555fd9.png)

Please assign me this work .
@rupeshmohanty @AshutoshGeek

**Comment by sakshi300699** [comment]
@manognyaa this is a really minor fix. Try to come up with some significant changes, I request you to please close this issue.
