### ISSUE TITLE
Create Edit Profile page

### ISSUE THREAD

**Issue by CoderGaurav01** [Spectrum-CETB/LesKollab#28]
**Describe the solution you'd like**
Creating an 'edit profile' option in the user dashboard

**Describe alternatives you've considered**
The edit details form can be a modal or a new webpage.

**Additional context**
According to me some user data should be readonly like email, while name, bio etc. fields should be editable. An additional option for change password can be given.

**Comment by CoderGaurav01** [comment]
I would like to work on this issue under GSSOC'21

**Comment by sakshi300699** [comment]
Seems interesting @CoderGaurav01 , Go ahead with this.

**Comment by Inventor77** [comment]
Can I also contritbute to this since its level three issue will be solved fast if two work on same

**Comment by simranbhalla3** [comment]
Hi I am a Gssoc'21 participant and would like to work on this issue , I have experience in css and js , please assign me this issue

**Comment by arpit456jain** [comment]
@sakshi300699 @rupeshmohanty kindly assign this to me I will make a PR as soon as possible

**Comment by rupeshmohanty** [comment]
@CoderGaurav01 Are you still working on this? Its been a long time. Should I assign this to someone else?

**Comment by CoderGaurav01** [comment]
You may assign it to others

**Comment by Inventor77** [comment]
> @CoderGaurav01 Are you still working on this? Its been a long time. Should I assign this to someone else?

@rupeshmohanty Sir I was the one who Asked first so please Assign it  to me

**Comment by arpit456jain** [comment]
@rupeshmohanty i am also interested in this issue i will make a PR in an hour

**Comment by rupeshmohanty** [comment]
> @rupeshmohanty i am also interested in this issue i will make a PR in an hour 

@arpit456jain @Inventor77 was the second person who asked to be assigned for this issue. So let's give him a shot.

**Comment by arpit456jain** [comment]
Ok

**Comment by arpit456jain** [comment]
> > @rupeshmohanty i am also interested in this issue i will make a PR in an hour
> 
> @arpit456jain @Inventor77 was the second person who asked to be assigned for this issue. So let's give him a shot.

@Inventor77 are you working on this issue.

@rupeshmohanty can I work on this issue .

**Comment by Inventor77** [comment]
> > > @rupeshmohanty i am also interested in this issue i will make a PR in an hour
> > 
> > @arpit456jain @Inventor77 was the second person who asked to be assigned for this issue. So let's give him a shot.
> 
> @Inventor77 are you working on this issue.
> 
> @rupeshmohanty can I work on this issue .

@arpit456jain Hello Arpit, I'm working on it sorry for being late on this. 
Stay safe

**Comment by arpit456jain** [comment]
ok no problem carry on @Inventor77

**Comment by rupeshmohanty** [comment]
@Inventor77 Any progress?

**Comment by Inventor77** [comment]
@rupeshmohanty Sorry sir, but i will not be able to Work on it please assign this issue  to @arpit456jain

**Comment by rupeshmohanty** [comment]
@Inventor77 Okay no problem!
