### ISSUE TITLE
Footer missing in home page 

### ISSUE THREAD

**Issue by hardikvarshney** [Spectrum-CETB/LesKollab#29]

**Comment by sakshi300699** [comment]
You can go ahead with the issue @hardikvarshney

**Comment by simranbhalla3** [comment]
Can i work on this issue? I can make footer using css and js , I am a Gssoc participant

**Comment by Inventor77** [comment]
@sakshi300699 Please mam assign me this issue I have Ideas to create  Footer with some normalized user friendly Animations

**Comment by hardikvarshney** [comment]
It is to bring to your notice that, I had created PR for this issue it was approved by all the mentors and was successfully merged.
Mentors are requested to close this issue.

**Comment by sakshi300699** [comment]
> 
> 
> @sakshi300699 Please mam assign me this issue I have Ideas to create Footer with some normalized user friendly Animations

@Inventor77 This issue has already been worked on. Please see to the issues which have not been worked on or create another issue describing your idea.

**Comment by sakshi300699** [comment]
This issue is closed.
