### ISSUE TITLE
Adding Contributor section in readme ( Automatically )

### ISSUE THREAD

**Issue by sahilempire** [Spectrum-CETB/LesKollab#32]
I will like to add a feature this will **update contributor list** in README.md **automatically** !! Will start to work on this issue **as soon as I get assigned !**

Thank You.

**Comment by sakshi300699** [comment]
@sahilempire This issue has already been created and assigned to another participant. Refer issue #17 for that. Kindly look for another issue.

**Comment by sahilempire** [comment]
@sakshi300699 okay then, I'm closing this issue.

Thank you.
