### ISSUE TITLE
UI Improvement ("Project Idea" Card)

### ISSUE THREAD

**Issue by Subhampreet** [Spectrum-CETB/LesKollab#34]
**Describe the bug**
The "Project Idea" Card is too simple. It can have a project repository icon, also social media handles of the project idea raiser for further communication, also the card UI can be improved to match the whole UI of the page.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version 89.0

**Comment by arpit456jain** [comment]
<img width="960" alt="cards" src="https://user-images.githubusercontent.com/55352601/115961216-0cb47400-a533-11eb-88c5-00dfa4eded85.png">

@rupeshmohanty I have tried to improve the ui of project cards its looking like this.



and there was a bug also . previously in the place of image of projects it was showing the image of profile pic of user.

I would like to make a PR for this and request to give it a level3 as i solved 2 issues in one

**Comment by arpit456jain** [comment]
<img width="960" alt="cards" src="https://user-images.githubusercontent.com/55352601/115961604-bc3e1600-a534-11eb-8875-8c2aea0fcbab.png">

**Comment by arpit456jain** [comment]
@rupeshmohanty please let me know whether the image is visible or not

**Comment by rupeshmohanty** [comment]
@arpit456jain Make a PR for this issue!
