### ISSUE TITLE
Changes in the Login/Register pop-up

### ISSUE THREAD

**Issue by capblack222** [Spectrum-CETB/LesKollab#36]
Describe the issue: The design of that pop-up is way to simple and also there is a constraint applied on it which make it change the pop from login to register. 
How to reproduce the issue: There could be some styling added to the login and register buttons to show which one is active and also some more styling to it, like some font change and some more styling.

And please assign this issue to me.

**Comment by anika-001** [comment]
Go ahead @capblack222

**Comment by capblack222** [comment]
Can I change the layout of the website like split the login and register buttons as the carousel makes like a slide show in the modal which makes it go back and forth after some time, so can I ? @anika-001

**Comment by anika-001** [comment]
Yes, that would be nice! Go ahead @capblack222 .

**Comment by capblack222** [comment]
Great! I will get on with it then!

**Comment by capblack222** [comment]
May I inculcate some Styling and font changes too? to make it look more attractive?

**Comment by anika-001** [comment]
Yes that would be great! Reviewing your changes currently.
