### ISSUE TITLE
Edit the Project info

### ISSUE THREAD

**Issue by Raghad-Khaled** [Spectrum-CETB/LesKollab#37]
**Is your feature request related to a problem? Please describe.**
there will be pop up window as Post project (get when clicked edit button that will be beside delete button) and has the information of the project and button call save which save the new data of project

**Comment by rupeshmohanty** [comment]
Already a modal is coming up when the post project option is clicked. And the delete post functionality exists too. So you can work on the edit the post part if you want to.

**Comment by Raghad-Khaled** [comment]
Yes, I want to work on edit post

**Comment by rupeshmohanty** [comment]
Then let me assign this issue to you.

**Comment by Ananyaagupta** [comment]
is the issue still open? i would like to work/collaborate too. @rupeshmohanty

**Comment by rupeshmohanty** [comment]
@Ananyaagupta Someone is already working on this issue, you can work on some other issue or you can create your own issue.
