### ISSUE TITLE
Toggle content /contact us/scrolling issue

### ISSUE THREAD

**Issue by lipsa199** [Spectrum-CETB/LesKollab#38]
Describe the issue:
 **when the webpage minimizes after that if you click the Toggle button for opening navbar then there scrolling is not working hence the 'contact us ' is not visible properly  **
![IMG20210318113902](https://user-images.githubusercontent.com/76063097/111581890-0fa7a080-87e0-11eb-9403-56a21e332144.jpg)

**Comment by rupeshmohanty** [comment]
This is the official site of our organization and this has not been registered as a GSSOC Project. So you can't contribute in this one.
