### ISSUE TITLE
Background color of buttons is messed up

### ISSUE THREAD

**Issue by satcasm** [Spectrum-CETB/LesKollab#39]
It seems when I fixed #21 , it messed up the background-color of other buttons too. I apologize for not paying attention to it at that moment.
Would like to fix it under GSSOC' 21.
Thanks!

Screenshot reference:
![image](https://user-images.githubusercontent.com/56315878/111595381-163f1380-87f2-11eb-81ff-1fa5c65d788d.png)

**Comment by simranbhalla3** [comment]
Hi I am a Gssoc'21 participant and would like to work on this issue , I have experience in css and js , please assign me this issue

**Comment by rupeshmohanty** [comment]
This works fine in my system.
