### ISSUE TITLE
(gsoc'21)  Mess in the responsiveness in phone view

### ISSUE THREAD

**Issue by arpit456jain** [Spectrum-CETB/LesKollab#40]
**Describe the bug**
There is a total mess in the phone view.
Navbar is messed up. button is messed up and background image is also messed up in short almost whole page is messed up in phone view . It is looking like this in phone view.
<img width="960" alt="les1" src="https://user-images.githubusercontent.com/55352601/111877000-3b38af80-89c7-11eb-90e3-d74f975aafe3.png">
<img width="960" alt="les2" src="https://user-images.githubusercontent.com/55352601/111877008-4390ea80-89c7-11eb-919e-7603727717d1.png">
<img width="960" alt="les3" src="https://user-images.githubusercontent.com/55352601/111877014-4c81bc00-89c7-11eb-9c57-7bf9e243cf74.png">

**To Reproduce**

**Expected behavior**
It should fully responsive in all screen 
**Screenshots**
I have to work on it currently i am unable to give any screenshots but if you assign me this i will give my best and will make it responsive as much as possible for screen as soon as possible . I am a gsoc'21 participant , kindly assign me this.
**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by sakshi300699** [comment]
@arpit456jain You can go ahead with this!

**Comment by arpit456jain** [comment]
@sakshi300699  Mam I had  solved this issue and created the pull request please check it i had also attached a video with it for reviewing it. Please check it.

**Comment by sakshi300699** [comment]
Sure @arpit456jain !
