### ISSUE TITLE
Uploaded files should have unique name!

### ISSUE THREAD

**Issue by asmitsirohi** [Spectrum-CETB/LesKollab#43]
While uploading profile pic or project pic there will be high chance that more than one pic can have same name.
Currently, If a random user uploaded different pic with same name it shows "Some error occurred while uploading your pic!"

Solution : While uploading a pic, unique name will we given to a particular pic.

**Comment by asmitsirohi** [comment]
please assign this issue to me under GSSOC'21

**Comment by ishubham21** [comment]
@asmitsirohi A suggestion from our side - To implement this feature, you can append the timestamp of each image with the name of that respective image.

**Comment by asmitsirohi** [comment]
Ok...I will consider that...

**Comment by asmitsirohi** [comment]
In pull request #48, I already resolved this issue.
