### ISSUE TITLE
Design a Logo for LesKollab

### ISSUE THREAD

**Issue by sakshi300699** [Spectrum-CETB/LesKollab#46]
<b>Create and design a logo</b> describing the website <b>LesKollab</b>, which would be added in the NavBar, Footer and Beside the name of the website.

**Comment by hardikvarshney** [comment]
I want to work on this issue.

**Comment by sakshi300699** [comment]
@hardikvarshney You can go ahead with this!

**Comment by hardikvarshney** [comment]
![logo1](https://user-images.githubusercontent.com/76947310/112745077-44c3a800-8fc3-11eb-8d51-ed16c7b8bbd3.png)
This is the brand logo I have chosen for the website.

**Comment by sakshi300699** [comment]
@hardikvarshney The design looks great!
You can go about adding this logo to the Navbar, Footer and Beside the name of the Tab and make a PR.
