### ISSUE TITLE
Full description of a project

### ISSUE THREAD

**Issue by rupeshmohanty** [Spectrum-CETB/LesKollab#5]
When an user clicks on the more option then they can check the full details including the description, screenshots of the project and how to contact the owner of the project for collaboration.

![image](https://user-images.githubusercontent.com/43889891/107857142-93bddf80-6e52-11eb-904f-0e4f4a281ceb.png)

**Comment by sukhpreet-singh1** [comment]
can you please assign me this issue?

**Comment by rupeshmohanty** [comment]
Hey sukhpreet! How do you plan to make the required changes?

**Comment by sukhpreet-singh1** [comment]
i can open the description in new page or can expand this only

**Comment by rupeshmohanty** [comment]
Hey sukhpreet! I have assigned this issue to you

**Comment by Vansh-Gupta4** [comment]
can i work on this?

**Comment by rupeshmohanty** [comment]
Okay lemme 

> can i work on this?

Yes

**Comment by rupeshmohanty** [comment]
> can i work on this?

Yes

**Comment by Sakshi0401** [comment]
As a GSSOC'21 participant I would like to contribute.
Can you please assign it to me ??

**Comment by feni-katharotiya** [comment]
@rupeshmohanty Hello, I am gssoc participant and would like to work on this issue.

**Comment by rupeshmohanty** [comment]
@Sakshi0401 @Vansh-Gupta4 @feni-katharotiya 
Hey guys,
This issue has been assigned to another contributor, so you guys can work on other issues or you can check for other issues in the project and create them and I will assign them to you.

**Comment by rk05-lenavo** [comment]
Hey , I am participant in GSSOC'21. Can you please assign this to me?

**Comment by rupeshmohanty** [comment]
> Hey , I am participant in GSSOC'21. Can you please assign this to me?

Hey @rk05-lenavo, This issue has already been assigned to another contributor, so please try some other issue or create your own issue.

**Comment by arpit456jain** [comment]
@rupeshmohanty 	can I give it a try ? its been a month you assigned this issue

**Comment by rupeshmohanty** [comment]
@sukhpreet-singh1 You still working on this? Any updates?

**Comment by rupeshmohanty** [comment]
@arpit456jain You can work on this issue now!

**Comment by arpit456jain** [comment]
@rupeshmohanty I have a doubt in this .
For Now we can only see the projects which we add we can't see the project of all Am I right or am i missing something.??
I need some guidance  since php is not my field I had work in php a long ago but suerly i can try it.


Till now i made this have a look and tell i am on right path or going wrong

https://user-images.githubusercontent.com/55352601/115110621-fa1dc600-9f99-11eb-8995-dd808936e455.mp4

**Comment by rupeshmohanty** [comment]
> @rupeshmohanty I have a doubt in this .
> For Now we can only see the projects which we add we can't see the project of all Am I right or am i missing something.??
> I need some guidance  since php is not my field I had work in php a long ago but suerly i can try it.
> 
> 
> Till now i made this have a look and tell i am on right path or going wrong
> 
> https://user-images.githubusercontent.com/55352601/115110621-fa1dc600-9f99-11eb-8995-dd808936e455.mp4
> 
> 

According to the code you can see all the posts now. You can check that by creating a post from another account.

**Comment by arpit456jain** [comment]
> > @rupeshmohanty I have a doubt in this .
> > For Now we can only see the projects which we add we can't see the project of all Am I right or am i missing something.??
> > I need some guidance  since php is not my field I had work in php a long ago but suerly i can try it.
> > Till now i made this have a look and tell i am on right path or going wrong
> > 
> >   
> >     
> >     les.new.mp4
> 
> According to the code you can see all the posts now. You can check that by creating a post from another account.

So my code is ok ??
May i create a pr for this ofcourse i will design the project description page better than this

**Comment by rupeshmohanty** [comment]
> > > @rupeshmohanty I have a doubt in this .
> > > For Now we can only see the projects which we add we can't see the project of all Am I right or am i missing something.??
> > > I need some guidance  since php is not my field I had work in php a long ago but suerly i can try it.
> > > Till now i made this have a look and tell i am on right path or going wrong
> > > 
> > >   
> > >     
> > >     les.new.mp4
> > 
> > According to the code you can see all the posts now. You can check that by creating a post from another account.
> 
> So my code is ok ??
> May i create a pr for this ofcourse i will design the project description page better than this

Yeah make a better design and then you can put a PR.
