### ISSUE TITLE
Contact Us section

### ISSUE THREAD

**Issue by arpit456jain** [Spectrum-CETB/LesKollab#54]
**Is your feature request related to a problem? Please describe.**
There should be a contact us page or section in website where user  can contact if he/she have any query. with validations

**Describe the solution you'd like**
I can make a separate page or add it in same page 
**Describe alternatives you've considered**

**Additional context**

**Comment by hardikvarshney** [comment]
I want to work on this issue.

**Comment by arpit456jain** [comment]
@rupeshmohanty sir kindly assign it to me I am gssoc'21 participant So I can create a PR.
I had already made contact section just waiting for your confirmation.

**Comment by rupeshmohanty** [comment]
@hardikvarshney Someone is already working on this issue. So you can work on other issues.

**Comment by hardikvarshney** [comment]
Okay

**Comment by arpit456jain** [comment]
@rupeshmohanty kindly suggest me should i make a separate page for contact section or a modal in same page 
like login/sign up

**Comment by arpit456jain** [comment]
@rupeshmohanty kindly review my PR #57
