### ISSUE TITLE
Complete Info of loggedin User!

### ISSUE THREAD

**Issue by asmitsirohi** [Spectrum-CETB/LesKollab#58]
There should be a option available, where logged in user can change his/her username or GitHub link or LinkedIn link or Bio or DP. 
Also, there should be a separate page where user can monitor all his/her profile.

To solve this issue there should be new page "user_info.php" attached with user's name at navigation bar, where users can manage their profile.

![image](https://user-images.githubusercontent.com/63240102/113083324-a3726700-91f9-11eb-9ad2-166953333bc4.png)

**Comment by asmitsirohi** [comment]
please assign this issue to me under GSSOC'21

**Comment by Inventor77** [comment]
@asmitsirohi Can I work with you on this Issue

**Comment by asmitsirohi** [comment]
@Inventor77 Actually, I have already done 80% of the required work. But you can further improve it when I'm done with it.

**Comment by Inventor77** [comment]
> @Inventor77 Actually, I have already done 80% of the required work. But you can further improve it when I'm done with it.

@asmitsirohi I just wanted to Learn this thing please Let me Work with you. No need of Assigning me on this Issue also i don't want any Points. Just to learn how this is made😁😁

**Comment by Inventor77** [comment]
@rupeshmohanty Sir its been many days and yet it is not solved, if @asmitsirohi is not working on it  can I take this Issue

**Comment by asmitsirohi** [comment]
@Inventor77 I'm working on it.

**Comment by rupeshmohanty** [comment]
@Inventor77 This issue has been assigned to @asmitsirohi, so let him work on it and you can work on some other open issues or you can create your own issue.

**Comment by asmitsirohi** [comment]
I have successfully completed the task!
Here is the screenshot,
![Screenshot_2021-04-11 LesKollab - User Info](https://user-images.githubusercontent.com/63240102/114313310-b21f1f00-9b13-11eb-8641-026b0b7fde8d.png)

But, when I try trying to import updated schema just to make final checks, I got some errors in updated schema..
Here is screenshot of errors
![image](https://user-images.githubusercontent.com/63240102/114313408-0aeeb780-9b14-11eb-9104-1d44bc11297d.png)

**Comment by rupeshmohanty** [comment]
@asmitsirohi Have you made a PR for this issue?

**Comment by asmitsirohi** [comment]
@rupeshmohanty sir, I creates a pull just now, i.e. pull request no. #99
