### ISSUE TITLE
Organized Code!

### ISSUE THREAD

**Issue by asmitsirohi** [Spectrum-CETB/LesKollab#59]
Whenever other contributor want to contribute new feature then he/she have to repeat code of header, footer, navbar and modal.

Solution: There should be separate files for header, footer, navbar and modal in components folder.

**Comment by asmitsirohi** [comment]
please assign this issue to me under GSSOC'21

**Comment by asmitsirohi** [comment]
@rupeshmohanty sir, please review it.

**Comment by rupeshmohanty** [comment]
This change in folders can lead to mix up and the application might crash.

**Comment by asmitsirohi** [comment]
But, sir I'm planning to make changes only in Explore folder, where only index.php file is present. All the components (which could be repeated i.e header, footer, modals, navbar in other files as well) of index.php file is save in components/common folder just like message.php file.
After doing this, These components is easily included in other files also this reduces the repeatable code.

These changes is applicable only on Dashboard (i.e Explore folder) not on whole project.

**Comment by rupeshmohanty** [comment]
Okay you can work on this issue. But provide a screen recording of the application after you solve this issue.

**Comment by asmitsirohi** [comment]
Definitely sir..
