### ISSUE TITLE
Missing! Login functionality for Admin.

### ISSUE THREAD

**Issue by hardikvarshney** [Spectrum-CETB/LesKollab#62]
@sakshi300699, We have created "Contact us" section but the message or query send by the users should be visible to a particular person(Admin). So, according to me there should be an admin login and after that admin functionality should be there in our website.

**Comment by sakshi300699** [comment]
@hardikvarshney where are you going to display the message to the Admin?

**Comment by hardikvarshney** [comment]
Messages sent by the user would be displayed on admin dashboard.

**Comment by sakshi300699** [comment]
So basically you are planning on to build a dashboard for the admin, right?

**Comment by hardikvarshney** [comment]
Exactly, because without admin panel messages or query sent by our user will only get stored in our database. Nobody would see them(query) and respond back to the user.

**Comment by sakshi300699** [comment]
That's great!

**Comment by hardikvarshney** [comment]
So, can I work on this.

**Comment by sakshi300699** [comment]
You can start working on this as soon as the Project Admin assigns this to you.

**Comment by hardikvarshney** [comment]
Okay.

**Comment by hardikvarshney** [comment]
@rupeshmohanty please add the level of this issue.

**Comment by hardikvarshney** [comment]
#63
