### ISSUE TITLE
Admin Dashboard showing number of projects, users and number of messages by users.

### ISSUE THREAD

**Issue by hardikvarshney** [Spectrum-CETB/LesKollab#64]
We have created a login page for admin. Now there should be a page for admin which shows number of users registered, number of projects on website and number of messages that are sent through contact us form.
On admin dashboard there will be a navbar, sidebar(showing links of logout, dashboard and view messages) and a main content on other side of page.

**Comment by rupeshmohanty** [comment]
@hardikvarshney Try to describe the issue properly using the issue template provided.

**Comment by hardikvarshney** [comment]
> @hardikvarshney Try to describe the issue properly using the issue template provided.

Issue described.

**Comment by hardikvarshney** [comment]
#91
