### ISSUE TITLE
[Gssoc'21] 404 page

### ISSUE THREAD

**Issue by arpit456jain** [Spectrum-CETB/LesKollab#72]
**Is your feature request related to a problem? Please describe.**
There was no 404 page .
I want to make a 404.html page for website

**Comment by arpit456jain** [comment]
@rupeshmohanty I had written the code to handle 404 error.
now i just wanted to ask should i make the 404 page from scratch or i can take it from internet which is freely available ? like i found this one. its looking pretty good
<img width="960" alt="404" src="https://user-images.githubusercontent.com/55352601/114303692-0f53aa00-9aed-11eb-82f0-ccbe41071229.png">

**Comment by arpit456jain** [comment]
<img width="960" alt="4042" src="https://user-images.githubusercontent.com/55352601/114303774-6194cb00-9aed-11eb-91e3-eb228a08d2f4.png">

this one is also good

**Comment by arpit456jain** [comment]
@sakshi300699 can you please guide me on this.

**Comment by ishubham21** [comment]
I guess it would be better if you could design a page from scratch, this would ensure a uniform theme and UI across the website.

**Comment by arpit456jain** [comment]
ok

**Comment by arpit456jain** [comment]
https://user-images.githubusercontent.com/55352601/114344443-791b9480-9b7d-11eb-98d0-ab7203e9f425.mp4


@ishubham21 how is it now?

**Comment by sakshi300699** [comment]
@arpit456jain This is looking good!
what do u think @rupeshmohanty @ishubham21 @anika-001 ?

**Comment by arpit456jain** [comment]
> @arpit456jain This is looking good!
> Did u make this from scratch?

No @sakshi300699  i had taken help from code pen

**Comment by arpit456jain** [comment]
@sakshi300699 kindly review my PR #80 

So i can make a PR for this

**Comment by arpit456jain** [comment]
@ishubham21 kindly review my open pr #80 
 So i can make pr for this

**Comment by sakshi300699** [comment]
> 
> 
> @sakshi300699 kindly review my PR #80
> 
> So i can make a PR for this

Sure!
