### ISSUE TITLE
Validation Required in "contact us" form.

### ISSUE THREAD

**Issue by hardikvarshney** [Spectrum-CETB/LesKollab#78]
Currently "Phone Number" field in contact us form is taking both text and numbers but it should take only numbers.

**Comment by hardikvarshney** [comment]
I want to work on this issue.

**Comment by hardikvarshney** [comment]
#81

**Comment by arpit456jain** [comment]
@hardikvarshney I think your PR is got merged , so you can close this issue as it creates confusion
