### ISSUE TITLE
Image dump into database

### ISSUE THREAD

**Issue by BeAgarwal** [Spectrum-CETB/LesKollab#8]
**Describe the bug**
The profile image should dump into the database rather than saving into the directory.

**To Reproduce**
While registering the user.

**Expected behavior**
The profile photo should dump into the database, as there is no need to store it in the directory.

Assign it to me. @rupeshmohanty

**Comment by rupeshmohanty** [comment]
Can you please tell me how are you gonna fetch the users profile photo without storing them in a directory?

**Comment by BeAgarwal** [comment]
I will store the profile photo in the database by converting it into the base64 format. And while displaying, it will just like a simple fetch query.

**Comment by rupeshmohanty** [comment]
I have assigned this issue to you, please send me a screenshot of the working changes once you are done

**Comment by BeAgarwal** [comment]
I want to know one thing. This process is increasing the computational speed. I have gone through many articles, all are saying that we can do it but it is not preferable to use.
So, whether will it be good for this project? If not, I will close this issue.
