### ISSUE TITLE
Add check-project.php Page

### ISSUE THREAD

**Issue by BeAgarwal** [Spectrum-CETB/LesKollab#9]
**Is your feature request related to a problem?**
Have a create the check-project.php page. It will show the full information of the project. 

**Describe the solution you'd like**
The Check-project.php page will have the full details related to the project.

**Describe alternatives you've considered**
No other alternative.

**Additional context**
Line 129 in Explore/index.php for **More...** about the project.

Assign to me. @rupeshmohanty

**Comment by rupeshmohanty** [comment]
I have assigned this issue to you

**Comment by arpit456jain** [comment]
@rupeshmohanty I think this is already done in my PR

**Comment by rupeshmohanty** [comment]
@BeAgarwal You can work on improving the UI of the page

**Comment by arpit456jain** [comment]
@BeAgarwal Are you working on this issue??

**Comment by arpit456jain** [comment]
https://user-images.githubusercontent.com/55352601/115399256-a1526580-a205-11eb-8d1e-700f6bb04ae9.mp4

@rupeshmohanty I had make some change in ui if you allow i would like to make a PR for this. Further ui can be enhanced by @BeAgarwal

**Comment by rupeshmohanty** [comment]
>  u.enhance.mp4 
> @rupeshmohanty I had make some change in ui if you allow i would like to make a PR for this. Further ui can be enhanced by @BeAgarwal

Looks good. Make a PR for this.

**Comment by arpit456jain** [comment]
> > u.enhance.mp4
> > @rupeshmohanty I had make some change in ui if you allow i would like to make a PR for this. Further ui can be enhanced by @BeAgarwal
> 
> Looks good. Make a PR for this.

Ok
