### ISSUE TITLE
Logout button for Admin.

### ISSUE THREAD

**Issue by hardikvarshney** [Spectrum-CETB/LesKollab#93]

**Comment by rupeshmohanty** [comment]
@hardikvarshney You could have created the logout button along with the dashboard. Why didn't you do that?

**Comment by hardikvarshney** [comment]
> @hardikvarshney You could have created the logout button along with the dashboard. Why didn't you do that?

I have not added because designing dashboard(specially the sidebar) has taken enough time. And I think coding of 3 pages(full design and development) is enough for level 3 issue.

**Comment by rupeshmohanty** [comment]
Logout button is a simple functionality which could have been added to that dashboard code too.

**Comment by hardikvarshney** [comment]
Okay then I will add it in my another PR for issue #92.

**Comment by hardikvarshney** [comment]
So, can I close this issue

**Comment by rupeshmohanty** [comment]
No you can work it this time. But in future, try to complete this small features in the same issue.

**Comment by hardikvarshney** [comment]
#102
