### ISSUE TITLE
Contributors section

### ISSUE THREAD

**Issue by arpit456jain** [Spectrum-CETB/LesKollab#97]
Recently i had seen in many websites there is contributors section in which username and pic of all contributors are listed .

We can also make a section for this i can write a loop in Java script for this .
All we have to do is make a arrays of all username and urls of user pics .

**Comment by rupeshmohanty** [comment]
This already exists. You can check this in the readme file.

**Comment by arpit456jain** [comment]
> This already exists. You can check this in the readme file.

No I mean on the index.php page below about and above faq .

**Comment by rupeshmohanty** [comment]
@arpit456jain This is not a requirement for this project for now. So am closing this issue.

**Comment by arpit456jain** [comment]
Ok
